# Transformar el texto en estructura de datos

##### Presentado por: Natali Angarita Escolar
##### Maestría en Estadística aplicada

In [2]:
import numpy as np
import pandas as pd
import re

from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
# 1. Corpus
documents = [
    "Political institutions shape public policy and influence democratic governance.",
    "Public policy decisions affect economic development and social outcomes.",
    "Democratic governance relies on institutions, political participation, and public trust."
]

# 2. Vectorizador
vectorizer = CountVectorizer(stop_words="english")

# 3. Ajuste y transformación
X = vectorizer.fit_transform(documents)

# 4. Mostrar vocabulario ordenado
print("Vocabulario:")
vocab = dict(sorted(vectorizer.vocabulary_.items(), key=lambda x: x[1]))
print(vocab)

# 5. Mostrar matriz documento-término
print("Matriz (documentos × términos):")
print(X.toarray())

# 6. Mostrar términos en orden de columnas
print("Términos (columnas):")
print(vectorizer.get_feature_names_out())

Vocabulario:
{'affect': 0, 'decisions': 1, 'democratic': 2, 'development': 3, 'economic': 4, 'governance': 5, 'influence': 6, 'institutions': 7, 'outcomes': 8, 'participation': 9, 'policy': 10, 'political': 11, 'public': 12, 'relies': 13, 'shape': 14, 'social': 15, 'trust': 16}
Matriz (documentos × términos):
[[0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0]
 [1 1 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 1 0 1 0 1 1 1 0 0 1]]
Términos (columnas):
['affect' 'decisions' 'democratic' 'development' 'economic' 'governance'
 'influence' 'institutions' 'outcomes' 'participation' 'policy'
 'political' 'public' 'relies' 'shape' 'social' 'trust']
